---
- name: This is my tasks for testing
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: install apache (apt)
      package:
        name: apache2
        state: present
    - name: install apache (yum)
      package:
        name: httpd
        state: present
