---
- name: Enable Intranet Services
  hosts: Redhat
  become: yes
  force_handlers: yes
  tasks:
    - name: Install httpd and firewalld
      yum:
        name:
          - httpd
          - firewalld
        state: latest
      notify: start httpd
    - name: Enable and Run Firewalld
      service:
        name: firewalld-wrong
        enabled: true
        state: started
    - name: firewalld permitt httpd service
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes
    - name: httpd enabled and running
      service:
        name: httpd
        enabled: true
        state: started
  handlers:
    - name: start httpd
      service: name=httpd state=restarted
    - name: Test html page is installed
      copy:
        content: "Welcome to the Mangesh.com intranet!\n"
        dest: /var/www/html/index.html

