---
 - name: This is my first play for installation of httpd
   hosts: all
   become: true
   tasks:
    - name: Installation of the web-server with httpd
      yum: name=httpd state=present
    
    - name: Creating project dicretory inside the httpd
      command: mkdir /tmp/mywebappsrv creates=/tmp/mywebappsrv

 - name: This is my second play for installation of git software
   hosts: Ubuntu
   become: true
   tasks:
     - name: Installation of version control
       action: yum name=git state=present 
