---
 - name: Installation of multiple packages
   hosts: Redhat
   tasks:
     - name: This is first method to create the loop
       yum:
         name: "{{ item }}"
         state: latest
       with_items:
         - vsftpd
         - tree
         - git
