---
 - name: Installation of multiple packages
   hosts: Redhat
   tasks:
     - name: This is first method to create the loop
       yum:
         name: ['vsftpd', 'tree', 'git']
         state: absent
